# Generated by Django 3.2 on 2021-06-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now=True),
        ),
    ]
