# Generated by Django 3.2 on 2021-06-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_auto_20210601_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rate_perday',
            field=models.IntegerField(default=0),
        ),
    ]
