# Generated by Django 3.2 on 2021-06-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_carbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now=True)),
                ('pickup_date', models.DateField(default='1999-12-14')),
                ('dropoff_date', models.DateField(default='1999-12-14')),
                ('pickup_address', models.CharField(max_length=100)),
                ('dropoff_address', models.CharField(max_length=100)),
                ('offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.offers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
